# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Will be generated for you, if you leave this blank.', unique=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('bloghero', models.ImageField(upload_to='/Users/Harsh/Level/simplyharsh/galepartners/gale-blog/galeblog/uploads/bloghero')),
                ('blogimage', models.ImageField(blank=True, null=True, upload_to='/Users/Harsh/Level/simplyharsh/galepartners/gale-blog/galeblog/uploads/blogimage')),
                ('body', models.TextField()),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Will be generated for you, if you leave this blank.', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory'),
        ),
    ]
